### ISSUE TITLE
Presentation Deck - Gather data

### ISSUE THREAD

**Issue by gmg300** [raise-da-woof/fetch#11]
Research data on why socializing your pet is important
- Stats
- Article links

**Comment by rwillowlevy** [comment]
https://www.dogtopia.com/blog/dog-socialization-benefits/
https://www.cesarsway.com/why-socialization-is-important/
https://www.petguide.com/petcare/dog/7-reasons-why-its-important-to-properly-socialize-your-dog/
https://topdogtips.com/socialize-dog-science/
