### ISSUE TITLE
Frontend - Updating user and pet doesn't update redux store

### ISSUE THREAD

**Issue by gmg300** [raise-da-woof/fetch#65]
When you hit update it changes the info on the profile page, if you navigate away using the links and navigate back to the profile the update is working as normal, but if you update the pet or user and reload the page it will revert to the pre-update information.

It looks like the update is saving to the DB and if you log in and out the updated info will appear. I think the redux store isn't being updated in the update function on the frontend and it's reloading the store when reloading the page.

**Comment by Alex-Bailon** [comment]
issue has been resolved
